### ISSUE TITLE
Orms +RME + text_profile

### ISSUE THREAD

**Issue by YendaHusk** [RMEx/orms#13]
A l'heure actuelle, lorsque l'on affiche un text via la commande `text_show` d'RME, il est possible de spécifier le profile du text avec ceux qui sont inscrit dans le fichier `ITextProfile.csv`.

Lorsque l'option `bitmap_font` de Orms est activé, les profils sont totalement ignorés. Normal, puisqu'il sont inutile et incompatible avec la font en bitmap généré par Orms.

Néanmoins, cela rend impossible le fait d'utiliser des couleurs dans les textes générés par `text_show`, mais reste possible dans les autres textes via la commande rm `\C[x]`

Du coup je me demander si il exister une autre façon d'appliquer une couleur au texte ou si c'était possible de fixer ça autrement ?

Merci

**Comment by BilouMaster** [comment]
Bonjour @YendaHusk 

ORMS est déjà pourvu d'une option qui change la portée du remplacement de texte, j'ai oublié le nom mais si tu change cette option tu auras le text_show de RME à nouveau comme avant... sans l'effet bitmap font.

Si ce n'est pas satisfaisant je t'invite à essayer de créer un patch qui modifie à la fois ORMS et RME pour intégrer par exemple le \C[...] dans text_show.

Dans tous les cas il s'agirait d'un troisième script "tampon" entre deux scripts, donc ton issue ne concerne pas directement ORMS... au sens où ce n'est ni un bug, ni un axe d'amélioration du script.
